random_text=[
    "Okay sir, I'm working on it",
    "Just a second sir",
    "Hold on a moment sir",
    "Let me check, sir",
    "I'm on it right now, sir",
    "Give me a minute sir",
    "Please wait a second, sir",
    "I'll get to it immediately, sir",
    "Just a moment, sir",
    "Hang tight, sir",
    "Okay sir, I'm working on it",
    "Just a second sir",
    "Hold on a moment sir",
    "Let me check, sir",
    "I'm on it right now, sir",
    "Give me a minute sir",
    "Please wait a second, sir",
    "I'll get to it immediately, sir",
    "Just a moment, sir",
    "Hang tight, sir",
    "Okay sir, I'm working on it",
    "Just a second sir",
    "Hold on a moment sir",
    "Let me check, sir",
    "I'm on it right now, sir",
    "Give me a minute sir",
    "Please wait a second, sir",
    "I'll get to it immediately, sir",
    "Just a moment, sir",
    "Hang tight, sir",
    "Okay sir, I'm working on it",
    "Just a second sir",
    "Hold on a moment sir",
    "Let me check, sir",
    "I'm on it right now, sir",
    "Give me a minute sir",
    "Please wait a second, sir",
    "I'll get to it immediately, sir",
    "Just a moment, sir",
    "Hang tight, sir",
    "Okay sir, I'm working on it",
    "Just a second sir",
    "Hold on a moment sir",
    "Let me check, sir",
    "I'm on it right now, sir",
    "Give me a minute sir",
    "Please wait a second, sir",
    "I'll get to it immediately, sir",
    "Just a moment, sir",
    "Hang tight, sir",
    "Okay sir, I'm working on it",
    "Just a second sir",
    "Hold on a moment sir",
    "Let me check, sir",
    "I'm on it right now, sir",
    "Give me a minute sir",
    "Please wait a second, sir",
    "I'll get to it immediately, sir",
    "Just a moment, sir",
    "Hang tight, sir",
    "Okay sir, I'm working on it",
    "Just a second sir",
    "Hold on a moment sir",
    "Let me check, sir",
    "I'm on it right now, sir",
    "Give me a minute sir",
    "Please wait a second, sir",
    "I'll get to it immediately, sir",
    "Just a moment, sir",
    "Hang tight, sir",
    "Okay sir, I'm working on it",
    "Just a second sir",
    "Hold on a moment sir",
    "Let me check, sir",
    "I'm on it right now, sir",
    "Give me a minute sir",
    "Please wait a second, sir",
    "I'll get to it immediately, sir",
    "Just a moment, sir",
    "Hang tight, sir",
    "Okay sir, I'm working on it",
    "Just a second sir",
    "Hold on a moment sir",
    "Let me check, sir",
    "I'm on it right now, sir",
    "Give me a minute sir",
    "Please wait a second, sir",
    "I'll get to it immediately, sir",
    "Just a moment, sir",
    "Hang tight, sir",
    "Okay sir, I'm working on it",
    "Just a second sir",
    "Hold on a moment sir",
    "Let me check, sir",
    "I'm on it right now, sir",
    "Give me a minute sir",
    "Please wait a second, sir",
    "I'll get to it immediately, sir",
    "Just a moment, sir",
    "Hang tight, sir",
    "Okay sir, I'm working on it",
    "Just a second sir",
    "Hold on a moment sir",
    "Let me check, sir",
    "I'm on it right now, sir",
    "Give me a minute sir",
    "Please wait a second, sir",
    "I'll get to it immediately, sir",
    "Just a moment, sir",
    "Hang tight, sir",
    "Okay sir, I'm working on it",
    "Just a second sir",
    "Hold on a moment sir",
    "Let me check, sir",
    "I'm on it right now, sir",
    "Give me a minute sir",
    "Please wait a second, sir",
    "I'll get to it immediately, sir",
    "Just a moment, sir",
    "Hang tight, sir",
    "Okay sir, I'm working on it",
    "Just a second sir",
    "Hold on a moment sir",
    "Let me check, sir",
    "I'm on it right now, sir",
    "Give me a minute sir",
    "Please wait a second, sir",
    "I'll get to it immediately, sir",
    "Just a moment, sir",
    "Hang tight, sir",
    "Okay sir, I'm working on it",
    "Just a second sir",
    "Hold on a moment sir",
    "Let me check, sir",
    "I'm on it right now, sir",
    "Give me a minute sir",
    "Please wait a second, sir",
    "I'll get to it immediately, sir",
    "Just a moment, sir",
    "Hang tight, sir",
    "Okay sir, I'm working on it",
    "Just a second sir",
    "Hold on a moment sir",
    "Let me check, sir",
    "I'm on it right now, sir",
    "Give me a minute sir",
    "Please wait a second, sir",
    "I'll get to it immediately, sir",
    "Just a moment, sir",
    "Hang tight, sir"
]
