Happy = [
    "Today, I am feeling great, Boss.",
    "Boss, I am doing well today.",
    "I am absolutely fine today, Boss.",
    "Feeling good today, Boss!",
    "Boss, I am perfectly okay today.",
    "Today is a good day, and I am fine, Boss.",
    "Boss, I am all good today.",
    "I am doing fantastic today, Boss.",
    "Boss, I am in a good mood today.",
    "Feeling fresh and fine today, Boss!",
    "Boss, I am feeling wonderful today.",
    "I am feeling awesome today, Boss!",
    "Boss, I am perfectly well today.",
    "Today is going great, and I am fine, Boss.",
    "I am totally fine today, Boss!",
    "Boss, I am doing excellent today.",
    "I am healthy and fine today, Boss.",
    "Boss, I am all set and fine today.",
    "Today is a great day, Boss, and I feel amazing.",
    "Boss, I am completely fine today!",
    "I am feeling relaxed and good today, Boss.",
    "Boss, I am fresh and fine today!",
    "I am feeling peaceful today, Boss.",
    "Everything is great, and I am fine today, Boss.",
    "Boss, I am in a good state today.",
    "Boss, I am feeling stable and fine today.",
    "I am doing pretty well today, Boss.",
    "Feeling absolutely fine today, Boss!",
    "Boss, I am happy and fine today.",
    "Boss, my mood is great today, and I feel fine.",
    "Today is a bright day, and I feel fine, Boss.",
    "Boss, I am completely okay today!",
    "I am full of energy and fine today, Boss!",
    "Boss, I am feeling super good today.",
    "I am totally okay and fresh today, Boss.",
    "Everything is smooth, and I am fine today, Boss.",
    "I am well and happy today, Boss!",
    "Boss, I am cheerful and fine today.",
    "Today is going well, and I am doing fine, Boss.",
    "Boss, I am doing fantastic today!",
    "I feel relaxed and great today, Boss.",
    "Boss, today I am fresh and active.",
    "I am in a good spirit today, Boss.",
    "Boss, I am enjoying my day and feeling good.",
    "Today is amazing, and I feel perfectly fine, Boss!",
    "I am in a positive mood today, Boss.",
    "Boss, I am all fresh and fine today!",
    "Boss, I am feeling good and happy today.",
    "Everything is going great, and I am fine today, Boss.",
    "I am doing well, Boss, thanks for asking.",
    "Boss, I am energized and doing fine today.",
    "Boss, I am in a cheerful mood today.",
    "I am feeling wonderful, Boss, today is great!",
    "Boss, I am doing fantastic, and my energy is high today.",
    "I am enjoying my time today, Boss!",
    "Boss, I am positive and feeling good today.",
    "Boss, today is a good day, and I am doing fine.",
    "I am perfectly healthy and fine today, Boss.",
    "Boss, I am stable and doing fine today.",
    "I feel super fresh today, Boss!",
    "Boss, I am in a joyful mood today.",
    "Feeling energetic and fine today, Boss!",
    "Boss, my health is great today, and I feel fine.",
    "Today is smooth, and I feel totally fine, Boss!",
    "I am fine, Boss, and my mind is clear today.",
    "Boss, I am optimistic and fine today.",
    "I am doing great, Boss, no complaints today!",
    "Boss, my energy is at its peak today, and I feel fine.",
    "I am having a wonderful day, Boss, feeling fine!",
    "Boss, today is peaceful, and I am doing fine.",
    "Everything is well-balanced today, Boss, and I am fine.",
    "I am feeling blessed today, Boss, and doing fine.",
    "Boss, I am fine and in a stable mood today.",
    "Today is stress-free, and I am feeling fine, Boss!",
    "Boss, my mood is light, and I feel fine today.",
    "Boss, I am content and feeling good today.",
    "Today is bright and joyful, and I feel fine, Boss.",
    "Boss, I am doing well today, and everything is good.",
    "Today is calm, and I am totally fine, Boss.",
    "Boss, my mind is relaxed, and I feel fine today.",
    "I am feeling satisfied and fine today, Boss!",
    "Boss, I am in a fresh mood and doing fine today.",
    "Boss, today is pleasant, and I feel amazing.",
    "I am enjoying my day and feeling fine today, Boss!",
    "Boss, I am in a peaceful state today.",
    "Today is a happy day, and I feel great, Boss!",
    "Boss, I am good and full of energy today.",
    "I am totally refreshed and fine today, Boss!",
    "Boss, I am enjoying every moment today and feeling fine.",
    "Boss, I feel energetic and fantastic today!",
    "Today is a lucky day, and I feel totally fine, Boss.",
    "Boss, my spirits are high, and I feel fine today!",
    "Boss, I am in a good vibe today and feeling fine.",
    "Boss, today is full of positivity, and I feel fine!",
    "I am calm, cool, and feeling fine today, Boss.",
    "Boss, my mind and body are in sync today, feeling great!",
    "I am totally at peace and fine today, Boss.",
    "Boss, everything is aligned, and I feel fine today.",
    "Today is inspiring, and I feel fine, Boss!",
    "Boss, I am mentally and physically fine today!",
    "Today is full of motivation, and I feel totally fine, Boss.",
    "Boss, I am in harmony with the day and feeling fine.",
    "I am appreciating today’s beauty and feeling fine, Boss!",
    "Boss, today is peaceful, and I feel fully fine.",
    "Boss, my heart is light, and I feel good today.",
    "I am flowing with positivity and fine today, Boss!",
    "Boss, I am simply enjoying today and feeling good.",
    "I am embracing happiness today, Boss, and feeling fine!",
    "Boss, today’s vibes are good, and I feel fine!",
    "I am aligned with good energy and fine today, Boss.",
    "Boss, I am grateful and fine today!",
    "Boss, my body and mind are refreshed today.",
    "Boss, I am balanced and doing fine today.",
    "Today is a meaningful day, and I feel fine, Boss!",
    "Boss, I am glowing with happiness today!",
    "Today is fantastic, and I feel completely fine, Boss.",
    "Boss, I am thriving and fine today!",
    "Boss, I am in sync with today’s rhythm and fine!",
    "Boss, I feel empowered and fine today!",
    "I am shining bright today, Boss, feeling fine!",
    "Boss, I am loving today, and I feel amazing!",
    "Boss, my energy is abundant today, feeling great!",
    "Today is golden, and I feel totally fine, Boss!",
    "Boss, my soul is light and feeling fine today!",
    "Boss, I am in a blissful mood today, feeling fine!",
    "I am at peace, Boss, and I feel totally fine!"
]
