OfflineDls = [
    "Boss, I am not connected to the internet, please connect the Wi-Fi.",
    "Hey boss, I am offline. Could you please connect the Wi-Fi?",
    "Boss, there’s no internet connection. Can you turn on the Wi-Fi?",
    "Sir, I’m not connected to the internet. Please enable Wi-Fi.",
    "Boss, I need internet access. Can you connect the Wi-Fi?",
    "Hey boss, I am not online. Please connect to Wi-Fi.",
    "Boss, I am unable to access the internet. Kindly turn on the Wi-Fi.",
    "Sir, my device is not connected to the internet. Please connect Wi-Fi.",
    "Hey boss, there’s no internet connection. Could you enable Wi-Fi?",
    "Boss, I am unable to get online. Can you please connect to Wi-Fi?",
    "Boss, I don’t have internet access. Kindly connect the Wi-Fi.",
    "Sir, I am disconnected from the internet. Please activate the Wi-Fi.",
    "Boss, I am not connected to Wi-Fi. Can you help?",
    "Hey boss, I am offline. Please connect Wi-Fi to get me online.",
    "Boss, there’s no internet here. Please connect to Wi-Fi.",
    "Boss, I can’t access the web. Please connect to Wi-Fi.",
    "Hey boss, the internet is down. Can you enable Wi-Fi?",
    "Sir, I’m not connected to the internet. Please turn on Wi-Fi.",
    "Boss, I can’t reach the web. Could you connect the Wi-Fi?",
    "Hey boss, my internet is off. Please turn on the Wi-Fi.",
    "Boss, I am disconnected from Wi-Fi. Could you reconnect?",
    "Sir, there’s no internet connection. Could you connect to Wi-Fi?",
    "Hey boss, I can’t browse. Can you please connect to Wi-Fi?",
    "Boss, I’m not connected to Wi-Fi. Could you help me out?",
    "Boss, the internet isn’t working. Can you enable Wi-Fi?",
    "Hey boss, no internet here. Can you connect Wi-Fi?",
    "Boss, there’s no Wi-Fi connection. Could you turn it on?",
    "Sir, I can’t get online. Please enable Wi-Fi.",
    "Boss, I’m not able to connect to the internet. Can you activate Wi-Fi?",
    "Hey boss, I need to be online. Can you connect Wi-Fi?",
    "Boss, my connection is down. Please enable Wi-Fi.",
    "Sir, I can’t access the internet. Could you turn on Wi-Fi?",
    "Boss, there’s no internet connection. Can you connect the Wi-Fi?",
    "Hey boss, I can’t access anything online. Please connect Wi-Fi.",
    "Boss, I’m not online. Can you connect Wi-Fi?",
    "Sir, I’m unable to connect to Wi-Fi. Can you help?",
    "Hey boss, no internet here. Please activate Wi-Fi.",
    "Boss, I’m unable to get online. Please connect the Wi-Fi.",
    "Boss, there’s no Wi-Fi here. Can you help me connect?",
    "Hey boss, no internet available. Please enable Wi-Fi.",
    "Boss, I am offline. Could you connect to the Wi-Fi?",
    "Sir, I am not online. Please turn on the Wi-Fi.",
    "Boss, my device is not connected to the internet. Can you connect the Wi-Fi?",
    "Hey boss, I can’t connect to the internet. Please enable Wi-Fi.",
    "Boss, I need Wi-Fi to access the internet. Can you turn it on?",
    "Sir, I’m not able to browse. Please connect to Wi-Fi.",
    "Boss, I’m not connected to Wi-Fi. Can you help me out?",
    "Hey boss, I need the internet. Can you enable Wi-Fi?",
    "Boss, I don’t have internet access. Could you connect Wi-Fi?",
    "Sir, my connection is down. Can you enable the Wi-Fi?",
    "Hey boss, no internet. Please connect Wi-Fi.",
    "Boss, I can’t access the web. Can you turn on the Wi-Fi?",
    "Sir, I need to get online. Could you connect Wi-Fi?",
    "Boss, there’s no internet connection available. Can you help me?",
    "Hey boss, I’m offline. Can you connect to the internet?",
    "Boss, I can’t connect. Could you turn on the Wi-Fi?",
    "Hey boss, I need internet. Please connect Wi-Fi.",
    "Boss, I don’t have a connection. Can you activate Wi-Fi?",
    "Sir, I’m offline. Can you turn on Wi-Fi?",
    "Boss, no internet here. Could you enable Wi-Fi?",
    "Hey boss, no connection. Please connect Wi-Fi.",
    "Boss, I’m disconnected. Please activate Wi-Fi.",
    "Hey boss, there’s no internet. Can you connect Wi-Fi?",
    "Boss, I can’t reach the web. Could you enable Wi-Fi?",
    "Sir, I’m offline. Can you connect the Wi-Fi?",
    "Boss, no connection to the web. Please connect Wi-Fi.",
    "Hey boss, I can’t connect. Can you help with the Wi-Fi?",
    "Boss, I need Wi-Fi to access the internet. Could you help?",
    "Sir, I’m offline. Please turn on Wi-Fi.",
    "Boss, my device isn’t connected. Please enable Wi-Fi.",
    "Hey boss, there’s no internet. Can you turn on Wi-Fi?",
    "Boss, I can’t connect to the web. Could you help me out?",
    "Sir, I need the internet. Can you connect the Wi-Fi?",
    "Boss, I’m unable to browse. Please activate Wi-Fi.",
    "Hey boss, no internet connection. Can you turn on Wi-Fi?",
    "Boss, I can’t reach the internet. Please connect Wi-Fi.",
    "Sir, I’m not online. Please connect to Wi-Fi.",
    "Boss, I need Wi-Fi to get connected. Can you help?",
    "Hey boss, no connection here. Please activate Wi-Fi.",
    "Boss, I can’t connect. Can you help me with the Wi-Fi?",
    "Sir, I am disconnected. Can you enable Wi-Fi?",
    "Boss, no internet here. Could you turn on Wi-Fi?",
    "Hey boss, there’s no Wi-Fi. Please connect it.",
    "Boss, I am not connected to the web. Can you turn on Wi-Fi?",
    "Sir, I can’t access the internet. Please connect Wi-Fi.",
    "Hey boss, I can’t get online. Could you connect Wi-Fi?",
    "Boss, I need to get connected. Can you turn on Wi-Fi?",
    "Hey boss, the internet is off. Can you enable Wi-Fi?",
    "Boss, I am not connected to Wi-Fi. Can you please help?",
    "Hey boss, I’m not connected to the web. Could you activate Wi-Fi?",
    "Boss, I can’t access the internet. Please enable Wi-Fi.",
    "Hey boss, no Wi-Fi. Can you help connect?",
    "Boss, I can’t connect to Wi-Fi. Could you enable it?",
    "Hey boss, no connection to the internet. Can you help?",
    "Boss, I can’t get online. Please activate Wi-Fi.",
    "Sir, I’m unable to access the web. Could you turn on Wi-Fi?",
    "Boss, I need the internet. Can you enable Wi-Fi?",
    "Hey boss, I am offline. Can you connect Wi-Fi?",
    "Boss, no internet here. Please connect Wi-Fi.",
    "Hey boss, can’t access the web. Could you turn on Wi-Fi?",
    "Boss, I’m offline. Could you activate the Wi-Fi?",
    "Sir, I can’t access the internet. Please turn on Wi-Fi.",
    "Boss, I’m disconnected from Wi-Fi. Please help connect.",
    "Hey boss, there’s no internet. Could you connect Wi-Fi?",
    "Boss, I can’t browse the web. Please connect Wi-Fi.",
    "Hey boss, no internet. Can you turn on Wi-Fi?",
    "Boss, I can’t get online. Could you enable Wi-Fi?",
    "Hey boss, I need internet access. Can you connect Wi-Fi?",
    "Boss, I’m offline. Can you enable Wi-Fi?",
    "Hey boss, no Wi-Fi connection. Could you turn it on?",
    "Boss, I am disconnected. Can you please activate Wi-Fi?",
    "Hey boss, there’s no internet. Can you enable Wi-Fi?",
    "Boss, I can’t get online. Could you help with the Wi-Fi?",
    "Sir, I’m offline. Could you connect Wi-Fi?",
    "Boss, there’s no connection. Could you enable Wi-Fi?"
]
