sentences = [
    "Hello I am Lucky. How can I help you?",
    "Greetings Lucky here. What can I do for you?",
    "Hi there I’m Lucky. How can I be of assistance?",
    "Hello it’s Lucky. How may I assist you today?",
    "Hey I’m Lucky. How can I help you out?",
    "Greetings I am Lucky. How can I serve you?",
    "Hello I am Lucky. What can I do for you today?",
    "Hi Lucky at your service. How can I assist you?",
    "Hey Lucky here. How may I help you?",
    "Hello I am Lucky. What do you need help with?",
    "Greetings from Lucky . How can I assist you today?",
    "Hi Lucky is here to help. How can I assist?",
    "Hello I am Lucky. How can I serve your needs?",
    "Hi there I’m Lucky. Let me know how I can assist.",
    "Hey Lucky at your service. How can I help you today?",
    "Greetings Lucky here. What can I do for you today?",
    "Hello, it’s Lucky. How can I make your day easier?",
    "Hi . Lucky here, ready to help. What do you need?",
    "Hello, I’m Lucky. How may I assist you today?",
    "Greetings from Lucky . How can I be of service?",
    "Hey there . I’m Lucky. What can I do for you?",
    "Hi, I’m Lucky. How can I be helpful today?",
    "Hello, I’m Lucky. Let me know how I can help you out.",
    "Hey . It’s Lucky. What can I do for you today?",
    "Hello . I’m Lucky. How can I assist you right now?",
    "Hi . Lucky here. How may I help you with something?",
    "Hello, I’m Lucky. How can I support you today?",
    "Greetings from Lucky . How can I assist you today?",
    "Hey . Lucky at your service. What can I do for you?",
    "Hello, I’m Lucky. How can I make things easier for you?",
    "Hi there . I’m Lucky. How may I help you today?",
    "Hello . Lucky here. How can I assist you with something?",
    "Greetings . I’m Lucky. How can I support you today?",
    "Hi . Lucky at your service. How can I help you?",
    "Hello, I’m Lucky. What can I do to assist you today?",
    "Hi . Lucky here. How can I be of help today?",
    "Hey, I’m Lucky. What can I help you with?",
    "Hello, it’s Lucky. How can I help you with that?",
    "Greetings from Lucky . How can I help today?",
    "Hi . Lucky here. What do you need help with today?",
    "Hello, I’m Lucky. How can I assist you right now?",
    "Hey . Lucky here. How can I be of help?",
    "Hi there . I’m Lucky. How can I serve you?",
    "Hello, I’m Lucky. How can I assist you today?",
    "Hi . Lucky here. What can I do to make things easier?",
    "Hello, it’s Lucky. How can I be of service to you?",
    "Hey . Lucky here. How can I assist you right away?",
    "Greetings from Lucky . How can I help you today?",
    "Hello, I’m Lucky. What would you like help with?",
    "Hi . Lucky here. What assistance do you need?",
    "Hey . It’s Lucky. How may I help today?",
    "Hello, I’m Lucky. How can I help you out today?",
    "Greetings from Lucky . How can I assist?",
    "Hi there . I’m Lucky. How can I help you today?",
    "Hey . Lucky at your service. What can I do for you today?",
    "Hello, I’m Lucky. What can I do to help you?",
    "Hi . Lucky here. How can I make things easier for you?",
    "Hello . Lucky here, at your service. How can I assist?",
    "Hey . I’m Lucky. How can I assist you right now?",
    "Hi there . I’m Lucky. How may I help you today?",
    "Hello, it’s Lucky. How can I support you today?",
    "Greetings from Lucky . What can I do for you today?",
    "Hi . Lucky here. What do you need help with today?",
    "Hello, I’m Lucky. How may I assist you with this?",
    "Hey . Lucky here. How can I help you today?",
    "Greetings from Lucky . How can I make things easier?",
    "Hi . Lucky here, ready to assist. How can I help?",
    "Hello . I’m Lucky. How can I help you right now?",
    "Hey . Lucky at your service. How may I help you today?",
    "Hi, I’m Lucky. How can I assist you today?",
    "Greetings from Lucky . How can I be of help?",
    "Hello . Lucky here. How may I assist with your needs?",
    "Hey, it’s Lucky. How can I serve you today?",
    "Hi there . Lucky here, ready to assist. What do you need?",
    "Hello, I’m Lucky. How can I assist you right away?",
    "Greetings . Lucky here. How can I help you today?",
    "Hi, I’m Lucky. What can I do for you right now?",
    "Hello, I’m Lucky. How can I help you today?",
    "Hi . Lucky at your service. How may I help you?",
    "Hey . Lucky here. How can I help you today?",
    "Greetings from Lucky . How can I assist you right now?",
    "Hello, I’m Lucky. What do you need assistance with?",
    "Hi . Lucky at your service. How can I assist?",
    "Hey, I’m Lucky. How can I help you today?",
    "Greetings from Lucky . What can I assist you with?",
    "Hello . Lucky here. How can I support you?",
    "Hi . Lucky here. How can I help you out?",
    "Greetings . I’m Lucky. How can I assist you?",
    "Hi . Lucky here. What can I help with today?",
    "Hello, it’s Lucky. How may I assist you today?",
    "Hey . Lucky here. How can I help you out?",
    "Hi, I’m Lucky. How can I assist you with this?",
    "Greetings from Lucky . How can I assist you today?",
    "Hello, it’s Lucky. What can I help you with?",
    "Hi . Lucky at your service. How can I help?",
    "Hey . It’s Lucky. How may I assist you?",
    "Greetings from Lucky . What can I do for you?",
    "Hello, I’m Lucky. How can I make things easier for you?",
    "Hi there . Lucky here. What do you need help with?",
    "Hey . Lucky here. How can I assist?",
    "Greetings from Lucky . What can I do for you?",
    "Hi . Lucky here. How may I assist today?",
    "Hello, I’m Lucky. How can I assist you right away?",
    "Hey . Lucky at your service. How can I help?",
    "Greetings from Lucky . How can I assist you right now?",
    "Hi . Lucky here. How can I make things easier?",
    "Hello, I’m Lucky. How can I assist you right now?",
    "Greetings . Lucky here. What can I do for you?",
    "Hi . Lucky here. How can I assist you with this?",
    "Hey . Lucky here. What do you need help with today?",
    "Hello, I’m Lucky. How can I assist you right away?",
    "Hi there . Lucky here. How can I help you out today?",
    "Greetings from Lucky . How may I assist you?",
    "Hello . I’m Lucky. How can I assist you today?",
    "Hey . Lucky here. What do you need help with?",
    "Hi there . Lucky here, how may I assist you today?",
    "Hello, I’m Lucky. How can I be of service?",
    "Hey . Lucky here. How can I assist you today?",
    "Hello, it’s Lucky. How may I help you?",
    "Hi . Lucky here. How can I assist today?",
    "Hello . Lucky at your service. How can I assist?",
    "Greetings . Lucky here. How may I help you today?",
    "Hi . Lucky here, how can I assist you with that?"
]

batteryDLG = [
    "Boss, your device is running very low on battery. Please charge it.",
    "Warning: Battery level is critically low, please plug in your charger.",
    "Attention: Your battery is running low. Connect to a power source.",
    "Alert: Battery level is dropping. Charge your device soon.",
    "Caution: Your device's battery is low. Please recharge immediately.",
    "Heads up! Your battery is running low. Time to charge up!",
    "Your device is low on battery, Boss. Please connect to a charger.",
    "Battery warning: Your device needs charging soon.",
    "Notice: Low battery! Connect to power to avoid shutdown.",
    "Reminder: Your battery is almost empty. Please charge it.",
    "Urgent: Your battery is running out. Charge your device now.",
    "Battery alert: Please charge your device to continue using it.",
    "Critical battery level detected. Please connect to a power source.",
    "Warning: Low battery! Charge your device to prevent it from turning off.",
    "Your battery is low, Boss. Make sure to plug it in soon.",
    "Battery running low: Please connect your charger.",
    "Attention: Your battery is almost depleted. Please recharge.",
    "Caution: Battery level is low. Connect to power as soon as possible.",
    "Heads up! Your device is low on battery. Time to recharge.",
    "Low battery alert: Please charge your device to keep it running.",
    "Notice: Your battery is running low. Connect to a charger.",
    "Warning: Battery critically low! Please charge your device now.",
    "Alert: Your device's battery is low. Time to plug in.",
    "Battery warning: Please charge your device to avoid shutdown.",
    "Reminder: Low battery! Connect to power soon.",
    "Urgent: Battery level is low. Recharge to continue using.",
    "Battery alert: Please connect your charger immediately.",
    "Critical: Your battery is low! Please charge now.",
    "Warning: Your device is running low on power. Recharge soon.",
    "Your battery is low, Boss. Plug it in for charging.",
    "Battery status: Low. Please connect to a power source.",
    "Attention: Your battery is almost out of power. Recharge!",
    "Caution: Low battery warning! Connect to a charger.",
    "Heads up! Your device's battery is low. Charge it soon.",
    "Battery alert: Please charge your device immediately.",
    "Notice: Battery running low. Connect to a power source.",
    "Warning: Your device needs charging now! Don't ignore it.",
    "Alert: Low battery detected! Charge your device right away.",
    "Critical alert: Battery level is very low. Please charge it.",
    "Your battery is running low! Time to recharge, Boss.",
    "Battery warning: Please connect to power to continue using.",
    "Reminder: Your device is low on battery. Plug it in.",
    "Urgent: Charge your device now to avoid shutdown.",
    "Battery alert: Please charge immediately to stay connected.",
    "Attention: Your battery is low! Don't let it die.",
    "Warning: Your device is running low on battery. Connect to power.",
    "Caution: Low battery detected! Please charge soon.",
    "Heads up! Your battery level is low. Time to charge.",
    "Battery alert: Your device needs a charge ASAP.",
    "Notice: Low battery! Please connect your charger.",
    "Warning: Your device is low on power. Recharge it now.",
    "Critical battery alert: Please connect to a power source."
]

lastChanceDLG = [
    "Boss, this is your last chance. Your battery is very low.",
    "Attention: Boss, this is your final warning. Battery is critically low.",
    "Warning: Boss, your battery is almost gone. This is your last chance!",
    "Caution: Boss, this is your last opportunity. Charge your device now!",
    "Boss, your battery is running dangerously low. This is your final chance.",
    "Last call, Boss! Your battery is very low. Charge it ASAP.",
    "Boss, this is it! Your battery is almost empty. Please recharge.",
    "Final alert: Boss, your battery is low. Time to plug in!",
    "Boss, your device is on its last legs! Charge it now.",
    "Urgent: Boss, this is your last chance. Battery level is critical.",
    "Boss, this is your final notice. Battery is running very low!",
    "Warning: Boss, your battery is about to die. Charge immediately!",
    "Boss, it's your last chance! Your battery is dangerously low.",
    "Attention: Boss, your battery is almost out. Recharge now!",
    "Boss, this is your last warning! Battery level is critically low.",
    "Final chance, Boss! Your battery is running low. Charge it soon.",
    "Boss, time is running out! Your battery is very low.",
    "This is it, Boss! Charge your device immediately—battery is low.",
    "Boss, your battery is on its last chance. Plug it in!",
    "Last warning, Boss! Your battery is very low.",
    "Caution: Boss, this is your last opportunity to charge.",
    "Boss, this is your final chance! Your battery needs power.",
    "Boss, urgent! This is your last chance before the device dies.",
    "Warning: Boss, your battery is very low. Charge now!",
    "Final call, Boss! Your device needs charging ASAP.",
    "Boss, your battery is critically low. This is your last chance!",
    "Last chance, Boss! Charge your device before it shuts down.",
    "Boss, this is it! Your battery is almost depleted. Recharge!",
    "Caution: Boss, this is your last chance to plug in.",
    "Boss, your device is low on battery. Time to charge it up!",
    "Urgent: Boss, your battery is running out. Final chance to recharge.",
    "Warning: Boss, this is your last chance to save your device.",
    "Boss, this is your final notice. Charge your battery soon.",
    "Last alert, Boss! Battery is very low. Charge immediately.",
    "Boss, your device is on its last chance! Please charge it.",
    "Attention: Boss, your battery is critically low. Time to recharge.",
    "Final notice, Boss! Your battery is running low.",
    "Boss, this is your last chance to connect to a power source.",
    "Warning: Boss, your battery level is dangerously low. Charge now!",
    "Caution: Boss, this is your last call. Charge your device.",
    "Boss, your battery is almost empty. This is your final chance!",
    "Final warning, Boss! Your device needs charging ASAP.",
    "Boss, this is your last opportunity. Recharge your battery.",
    "Attention: Boss, your battery is low. Final chance to plug in.",
    "Boss, this is your last warning! Charge your device immediately.",
    "Last chance, Boss! Your battery is critically low.",
    "Boss, your device is low on power. This is your final chance!",
    "Warning: Boss, your battery is running very low. Recharge now!",
    "Final alert: Boss, this is your last chance to charge your device."
]


batteryLowDLG = [
    "Boss, let me tell you. Your battery is very low.",
    "Attention: Boss, just to inform you, your battery is critically low.",
    "Warning: Boss, I want to let you know that your battery is almost gone!",
    "Caution: Boss, just so you know, your battery needs charging now!",
    "Boss, I must inform you, your battery is running dangerously low.",
    "Last call, Boss! Just a reminder, your battery is very low. Charge it ASAP.",
    "Boss, just to let you know, your battery is almost empty. Please recharge.",
    "Final alert: Boss, I want to inform you that your battery is low. Time to plug in!",
    "Boss, your device is on its last legs! Just so you know, charge it now.",
    "Urgent: Boss, just to remind you, your battery level is critical.",
    "Boss, this is important! Your battery is very low. Please charge immediately!",
    "Attention: Boss, just to inform you, your battery is about to die.",
    "Boss, I need to let you know, this is your last chance! Your battery is dangerously low.",
    "Final chance, Boss! Just so you know, your battery is running low. Charge soon.",
    "Boss, time is running out! Just to remind you, your battery is very low.",
    "This is it, Boss! Charge your device immediately—your battery is low.",
    "Boss, I must let you know, your battery is on its last chance. Plug it in!",
    "Last warning, Boss! Just to inform you, your battery is very low.",
    "Caution: Boss, this is your last opportunity to charge before it dies.",
    "Boss, just to remind you, this is your final chance! Your battery needs power.",
    "Boss, urgent! Just a heads up, your battery is running out. Final chance to recharge.",
    "Warning: Boss, just so you know, your battery is very low. Charge now!",
    "Final call, Boss! Your device needs charging ASAP. Just to inform you.",
    "Boss, just to let you know, your battery is critically low. This is your last chance!",
    "Last chance, Boss! Just so you know, charge your device before it shuts down.",
    "Boss, this is it! Just to inform you, your battery is almost depleted. Recharge!",
    "Caution: Boss, just to remind you, this is your last chance to plug in.",
    "Boss, your device is low on battery. Just to let you know, time to charge it up!",
    "Urgent: Boss, just to inform you, your battery is running out. Final chance to recharge.",
    "Warning: Boss, just so you know, this is your last chance to save your device.",
    "Boss, I must let you know, this is your final notice. Charge your battery soon.",
    "Last alert, Boss! Just to inform you, your battery is very low. Charge immediately.",
    "Boss, your device is on its last chance! Just so you know, please charge it.",
    "Attention: Boss, just to remind you, your battery is critically low. Time to recharge.",
    "Final notice, Boss! Just to let you know, your battery is running low.",
    "Boss, this is your last chance to connect to a power source. Just so you know.",
    "Warning: Boss, just to inform you, your battery level is dangerously low. Charge now!",
    "Caution: Boss, this is your last call. Just so you know, charge your device.",
    "Boss, just to let you know, your battery is critically low. This is your final chance!",
    "Final alert: Boss, I want to inform you that this is your last chance to charge.",
    "Boss, your battery is below 50%. Just a heads up that it’s time to charge.",
    "Attention: Boss, your battery is below half. Charge soon to keep it running.",
    "Warning: Boss, your battery is less than 50%. It's a good time to plug in!",
    "Boss, just so you know, your battery is below 50%. Recharge when you can.",
    "Caution: Boss, your battery is under half. Make sure to charge it soon.",
    "Boss, your battery is running low! Just so you know, it's below 50%.",
    "Alert: Boss, your battery is now below 50%. Please connect to power."
]

batteryFullDLG = [
    "Boss, your battery is at 100 percent. Please unplug it.",
    "Attention: Boss, your battery is fully charged at 100 percent. Unplug it now.",
    "Warning: Boss, your battery is at full capacity. Time to disconnect!",
    "Caution: Boss, your battery is 100 percent charged. Please unplug it!",
    "Boss, just a reminder, your battery is at 100 percent. Unplug it to save energy.",
    "Final notice: Boss, your battery is full at 100 percent. It's time to disconnect.",
    "Boss, your device is fully charged! Please unplug it to prevent overcharging.",
    "Urgent: Boss, your battery has reached 100 percent. Please unplug it now!",
    "Boss, this is important! Your battery is fully charged. Disconnect it!",
    "Attention: Boss, your battery level is at 100 percent. Please unplug immediately.",
    "Boss, your battery is at maximum capacity. It's time to unplug it.",
    "Caution: Boss, your battery is fully charged at 100 percent. Please disconnect!",
    "Boss, just so you know, your battery is at 100 percent. Unplug to save energy.",
    "Warning: Boss, your device is at full charge. Please unplug it now.",
    "Final alert: Boss, your battery is 100 percent charged. Time to disconnect!",
    "Boss, your battery is fully charged! Please unplug to avoid damage.",
    "Attention: Boss, your battery is at 100 percent. Disconnect it for safety.",
    "Boss, just a heads up, your battery is fully charged. Please unplug it.",
    "Caution: Boss, your battery is at 100 percent. Unplug it to save battery life.",
    "Boss, your battery has reached full charge! Please disconnect it now.",
    "Warning: Boss, your battery is at 100 percent. It's time to unplug.",
    "Final notice: Boss, your device is fully charged. Unplug it for safety.",
    "Boss, this is important! Your battery is at maximum capacity. Unplug now!",
    "Attention: Boss, your battery is fully charged. Please unplug it immediately.",
    "Caution: Boss, your battery is at 100 percent. Please disconnect it!",
    "Boss, just to inform you, your battery is at full charge. Unplug to preserve it.",
    "Warning: Boss, your battery is now at 100 percent. Unplug it!",
    "Final alert: Boss, your battery has reached full capacity. Please unplug!",
    "Boss, your battery is at 100 percent charged. It's time to disconnect.",
    "Attention: Boss, your battery is fully charged. Unplug it now.",
    "Caution: Boss, your battery is at maximum capacity. Please disconnect it.",
    "Boss, your device is fully charged at 100 percent. Time to unplug!",
    "Warning: Boss, your battery is full. Unplug it for optimal performance.",
    "Final notice: Boss, your battery is at 100 percent. Please unplug it.",
    "Boss, just a reminder that your battery is fully charged. Please disconnect it.",
    "Attention: Boss, your battery has reached full charge. Unplug immediately.",
    "Caution: Boss, your battery is at 100 percent. Disconnect it for safety.",
    "Boss, your battery is fully charged! Time to unplug it now.",
    "Warning: Boss, your battery is at maximum capacity. Please disconnect.",
    "Final alert: Boss, your battery is at 100 percent. Unplug it to avoid overcharging.",
    "Boss, your device is fully charged. Please unplug to preserve battery health.",
    "Attention: Boss, your battery is at 100 percent. Time to disconnect it.",
    "Caution: Boss, your battery is fully charged. Unplug it to save energy.",
    "Boss, just so you know, your battery is at 100 percent. Please unplug it now."
]


chargingDLG = [
    "Boss, plugging successful! Your device is charging now.",
    "Great news, Boss! The device is plugged in and charging.",
    "Boss, successful connection! Your device is now charging.",
    "Boss, you're all set! Your device is charging successfully.",
    "Charging complete, Boss! Your device is now plugged in.",
    "Boss, you're good to go! The device is charging now.",
    "Boss, plugging was a success! Your device is charging.",
    "Success, Boss! Your device is now receiving power.",
    "Boss, the connection is successful! Your device is charging.",
    "Boss, your device is plugged in and charging successfully.",
    "Awesome, Boss! Your device is charging now.",
    "Boss, everything's set! Your device is now charging.",
    "Boss, the device is charging successfully. You're good!",
    "Boss, charging initiated! Your device is now plugged in.",
    "Fantastic, Boss! Your device is charging properly.",
    "Boss, connection established! Your device is charging now.",
    "Boss, your device is now charging. Plugging was successful!",
    "Charging started, Boss! Your device is plugged in.",
    "Boss, your device is charging. Connection successful!",
    "Boss, the device is now charging. Plugging successful!",
    "Boss, great job! Your device is successfully charging.",
    "Boss, the charging process has started. Your device is plugged in.",
    "Boss, your device is now connected and charging.",
    "Charging successful, Boss! Your device is plugged in.",
    "Boss, your device is now charging. Connection successful!",
    "Boss, everything's in order! Your device is charging.",
    "Boss, charging successful! Your device is now receiving power.",
    "Boss, you're all set! The device is charging now.",
    "Boss, the connection is successful! Your device is charging.",
    "Boss, successful plugging! Your device is now charging.",
    "Boss, your device is now charging successfully.",
    "Boss, the charging has started! Your device is plugged in.",
    "Boss, your device is plugged in. Charging successful!",
    "Success! Boss, your device is now charging.",
    "Boss, everything is set! Your device is charging now.",
    "Charging complete, Boss! Your device is successfully plugged in.",
    "Boss, your device is now charging. Plugging was successful!",
    "Boss, you're good to go! The device is charging now.",
    "Boss, successful connection! Your device is now charging.",
    "Boss, you're all set! Your device is charging successfully.",
    "Fantastic news, Boss! The device is charging now.",
    "Boss, the connection is successful! Your device is charging.",
    "Boss, your device is charging. Plugging was a success!",
    "Boss, the device is charging now. Connection successful!",
    "Boss, great job! Your device is successfully charging.",
    "Boss, the charging process has started. Your device is plugged in.",
    "Boss, your device is now connected and charging.",
    "Charging successful, Boss! Your device is plugged in.",
    "Boss, your device is now charging. Connection successful!",
    "Boss, everything's in order! Your device is charging.",
    "Boss, charging successful! Your device is now receiving power."
]

batteryPowerDLG = [
    "Boss, your device is unplugged. You're running on battery power.",
    "Attention, Boss! The device is unplugged and using battery power.",
    "Boss, your device has been unplugged. Running on battery now.",
    "Caution, Boss! Your device is unplugged and operating on battery.",
    "Boss, the device is now unplugged. You're on battery power.",
    "Boss, your device is disconnected. You're relying on battery now.",
    "Boss, your device is unplugged. Time to save battery power!",
    "Warning, Boss! The device is unplugged and using battery.",
    "Boss, your device has been unplugged. Running on battery.",
    "Boss, your device is now unplugged. Battery power is in use.",
    "Boss, attention! Your device is unplugged and on battery.",
    "Boss, your device is unplugged. Please conserve battery power.",
    "Caution, Boss! The device is running on battery power now.",
    "Boss, your device is unplugged. Monitor your battery level.",
    "Boss, your device has been unplugged. You're on battery now.",
    "Boss, your device is disconnected. Battery power is active.",
    "Boss, your device is now unplugged. Time to manage battery.",
    "Boss, the device is unplugged. You're using battery power.",
    "Boss, your device is unplugged. Please keep an eye on battery.",
    "Boss, caution! Your device is unplugged and on battery power.",
    "Boss, your device is unplugged. Remember to charge it soon!",
    "Boss, your device is now unplugged. Running on battery.",
    "Attention, Boss! Your device is unplugged and using battery.",
    "Boss, your device is disconnected. Battery power is now in use.",
    "Boss, your device has been unplugged. Monitor your battery.",
    "Caution, Boss! The device is unplugged. You're on battery now.",
    "Boss, your device is unplugged. Conserve battery power!",
    "Warning, Boss! Your device is unplugged and on battery.",
    "Boss, your device is unplugged. Please charge soon.",
    "Boss, your device has been unplugged. Running on battery now.",
    "Boss, your device is now unplugged. You're using battery.",
    "Boss, attention! Your device is unplugged and on battery power.",
    "Caution, Boss! The device is now unplugged. Monitor battery.",
    "Boss, your device is unplugged. Please save battery power.",
    "Boss, your device is now unplugged. Battery is in use.",
    "Boss, the device is unplugged. You're running on battery.",
    "Attention, Boss! Your device is unplugged and using battery.",
    "Boss, your device is disconnected. You're on battery now.",
    "Boss, your device has been unplugged. Time to check battery.",
    "Caution, Boss! The device is unplugged. You're on battery power.",
    "Boss, your device is unplugged. Monitor your battery level.",
    "Boss, your device has been unplugged. You're on battery power.",
    "Boss, your device is unplugged. Please charge soon.",
    "Attention, Boss! Your device is unplugged and running on battery."
]

closedlg = [
    "closing",
    "close",
    "just a second sir",
    "got it sir",
    "closing now",
    "shutting down",
    "done",
    "almost there",
    "finished",
    "shutting it",
    "stopping",
    "closing up",
    "completed",
    "almost done",
    "closing the door",
    "we're done here",
    "closing it up",
    "all set",
    "just a moment",
    "closing this now",
    "it's over",
    "closing it shortly",
    "wrapped up",
    "it's finished",
    "closing out",
    "wrapped up now",
    "almost finished",
    "done with it",
    "take care",
    "it’s done",
    "turning off now",
    "it's closed",
    "shutting it down",
    "all done",
    "shut it off",
    "everything's set",
    "closing shortly",
    "just wrapping up",
    "everything's finished",
    "closing this window",
    "done with that",
    "shut now",
    "almost closed",
    "we're finished here",
    "we're done",
    "finishing up",
    "getting it closed",
    "sealing it up",
    "shut it",
    "closing the session"
]